Level 4: フルーツの動きを制限しよう
himura-shitara/suika-game-3d pull request #23
Opened 2024-05-13 19:56 UTC by himura-shitara

2024-05-14 08:06 UTC, touko1125 commented
透明な壁を配置する感じか
作業量自体は少ないけれど、「動きを制限→透明な壁を置こう」の発想ができるかな、、
少し先のレベルでもいいかもと思ったり

2024-05-17 05:34 UTC, himura-shitara commented
> 透明な壁を配置する感じか 作業量自体は少ないけれど、「動きを制限→透明な壁を置こう」の発想ができるかな、、 少し先のレベルでもいいかもと思ったり

わからなかったら飛ばせる問題ではあるということを踏まえて適当に配置したんですが、もう少し先のレベルになるんでしょうか？
先のレベルにするとしてどこのレベルにするのか、という話もあると思う。

2024-05-20 12:47 UTC, touko1125 requested changes
頼みます

2024-05-23 15:12 UTC, himura-shitara commented
面倒臭いのでレベル据え置きで、問題側に発想の難易度高いかもという文面を挟む感じで対応しようかなと思います、、、！
飛ばしてもいい問題ではあるので手がつかなかったら飛ばしてもらう感じで！

2024-05-23 15:33 UTC, merged