Level 8: 同種のフルーツが接触した際に上位のフルーツに変化するようにしてみよう
himura-shitara/suika-game-3d pull request #27
Opened 2024-05-13 20:16 UTC by himura-shitara

2024-05-13 20:25 UTC, himura-shitara commented on SuikaGame3D/Assets/Scripts/FruitsCombine.cs
> +                        Vector3.Lerp(
Vector3.Lerp について説明を加えた方が良い

2024-05-13 20:25 UTC, himura-shitara commented on SuikaGame3D/Assets/Scripts/FruitsCombine.cs
> +                if (nextFruit is not null)
is not はやばい。!= にしよう。
あと普通にバグの原因になっている。

2024-05-20 12:49 UTC, touko1125 requested changes
頼みます

2024-05-23 17:12 UTC, himura-shitara commented on SuikaGame3D/Assets/Scripts/FruitMove.cs
> +        _fruitRb.useGravity = false;
うるせー！

2024-05-23 17:13 UTC, himura-shitara commented on SuikaGame3D/Assets/Scripts/FruitMove.cs
> +        _fruitRb.useGravity = false;
もうマージしちゃった

2024-05-23 17:47 UTC, merged